### ISSUE TITLE
I can not find your pubilication.

### ISSUE THREAD

**Issue by phamthaihoangtung** [silknow/multimodal_cultural_heritage#1]
Can you publish your work on how to create this dataset, please? How can you label it? And what is your baseline? Thanks.

**Comment by rtroncy** [comment]
You can read several documents (called deliverables) as how we have developed the SILKNOW knowledge graph at https://silknow.eu/index.php/deliverables/. As written in the README, the dataset being used in this paper is available at https://zenodo.org/record/6590957 and is itself an excerpt of the entire SILKNOW Knowledge Graph available at https://zenodo.org/record/5743090. The entire code to develop the SILKNOW knowledge graph is open source, see https://github.com/silknow/converter but do have a look at the other repositories, such as the crawlers to get the rough data from the museums.
